spring:
  datasource:
    url: jdbc:h2:~/alunos;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
    drive-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true